---
title: '121'
author: "Tung-Wei"
date: "2019年9月11日"
output: html_document
---
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext)

font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```
```{r} 
df_gatherExample <- data.frame(
  country=c("A","B","C"),
  `1999`=c("0.7k","37k","212k"),
  `2000`=c("2k","80k","213k"),
  check.names = F
)
```


```{r}  
df_gatherExample
gather(df_gatherExample,
       `1999`,`2000`,
       key="年份",value="人口")
```

```{r}
library(readr)
collegeData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/103_student.csv")
```

```{r}
collegeData 
gather(collegeData,
      contains("生"),
       key="類別",value="人數")
```

```{r}
library(readr)
df_taoyuanMarriage <- read_csv("https://data.tycg.gov.tw/opendata/datalist/datasetMeta/download?id=f95d1a33-ec56-44c5-a9ec-3afba8157e39&rid=fd2070ef-7431-4f9c-bc3a-82d7bfbcd2fb")
```

```{r}
df_taoyuanMarriage
gather(df_taoyuanMarriage,
      -月份區域別,
       key="月份",value="人數") -> marriage_gather
df_taoyuanMarriage%>%
gather(
       ends_with("月"),
       key="月份",value="對數"
      )%>%group_by(月份區域別)%>%summarise(結婚最高峰月份=which.max(對數))
```


```{r}
df_spreadExample <- data.frame(
  id = c(1,1,1,2,2,2),
  var = c("花朶萼片長度", "學名", "總類數"),
  value = c(5.1, "setosa", 1, 
            7.0, "versicolor", 2))
```
```{r}
df_spreadExample
spread(df_spreadExample,
       var,value)
```

```{r}
df_twbankExchangeRate <- read_csv("http://www.bot.com.tw/Govinfo/opendata/csv/151/20180101-20181231-FXCRT.csv")
df_twbankExchangeRate %>%
  select(-即期賣出匯率)%>%
  spread(幣別,即期買入匯率)
```

```{r}
df_twbankExchangeRate %>%
  mutate(
    幣別= as.factor(幣別),
    即期買入匯率= as.double(即期買入匯率),
    即期賣出匯率= as.double(即期賣出匯率)
  )
```

```{r}
library(readr); library(dplyr)
# 線上引入原始資料成字串向量
read_lines("http://www.taifex.com.tw/data_gov/taifex_open_data.asp?data_name=DailyForeignExchangeRates") ->
  originalLines

# 將字串由CP950編碼改成UTF8再讀成data frame data2
originalLines %>%
  iconv(from="CP950",to="UTF8") %>% 
  read_csv() -> data2
```

#作業前都要改 並且從HISTORY放進來#
```{r}
library(readr)
taifex_open_data <- read_csv("http://www.taifex.com.tw/data_gov/taifex_open_data.asp?data_name=DailyForeignExchangeRates",
locale = locale(encoding = "BIG5"))
View(taifex_open_data)

```

```{r}
library(readr)
subsetDataTWbank <- read_csv("https://www.dropbox.com/s/t8ulj3d7cgl8jh5/subsetDataTWbank.csv?dl=1")

library(ggplot2)
subsetDataTWbank%>%
  
ggplot()+
  geom_line(
    aes(x=西元年月,y=`定存利率-一個月-固定`)
  )+
  geom_point(
    aes(x=西元年月,y=`定存利率-一個月-固定`)
  )
```

```{r}
subsetDataTWbank%>%
gather(
      contains("定存"),
       key="期數",value="利率") -> gatherTW

library(ggplot2)
gatherTW%>%
  
ggplot()+
  geom_point(
    aes(x=`期數`,y=`利率`)
  )
```

```{r}
gatherTW %>%
  ggplot()+
    geom_line(
      aes(x=西元年月,y=利率,color=期數)
    )
```
#改時間#
```{r}
twCalendar %>%
  # 取出字串中的數字部份
  stringr::str_extract_all("[:digit:]+") %>%
  # 將每個日期的「年」數字加上1991再合併年月日成為`yyyy-mm-dd`格式
  purrr::map_chr(
             function(x) {
               x1=as.integer(x[[1]])+1911
               x[[1]]=as.character(x1)
               stringr::str_c(x,collapse="-")
             }
             ) -> westernCalendar
```

subsetDataTWbank %>%
  mutate(
    年月=年月 %>%
      stringr::str_extract_all("[:digit:]+") %>%
      purrr::map_chr(
                 function(x) {
                   x1=as.integer(x[[1]])+1911
                   x[[1]]=as.character(x1)
                                stringr::str_c(x,collapse="-")
                 }
                 ),
    年月日=stringr::str_c(年月,"01",sep="-"),#這邊是字串#
    西元年月日=lubridate::ymd(年月日) #這才是data#
  )